import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'
import './globals.css'
import Navbar from './components/navbar'
import ClientOnly from './components/utils/ClientOnly'
import Register from './components/modal/Register'
import ToastProvider from './components/providers/ToastProvider'
import LoginModal from './components/modal/Login'
import getCurrentUser, { getSession } from './actions/getCurrentUser'
import RentModals from './components/modal/rent/RentModals'
import SearchModal from './components/modal/SearchModal'
import EmptyState from './components/main/EmptyState'
import Button from './components/utils/button/Button'
import Link from 'next/link'
import Container from './components/utils/Container'
import Heading from './components/utils/heading/Heading'

const inter = Nunito({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
    const currentUser = await getCurrentUser()
  return (
    <html lang="en">
      <body className={inter.className}>
              <ClientOnly>
                <ToastProvider />
                <RentModals />
                <SearchModal />
                <LoginModal />
                <Register />
                {
                  currentUser ? (
                    <Navbar currentUser={currentUser}/>
                  ) : null
                }
              </ClientOnly> 
              <div className='pt-28 pb-20'>
                {children}
              </div> 
        
        </body>
    </html>
  )
}
